-- Задание №3
-- 3.1 Пользователи, добавившие и прослушавшие > 10% книгу 'Coraline'
SELECT
	AB1.TITLE,
	COUNT(DISTINCT AS1.USER_ID) AS ADDED_USERS,
	COUNT(DISTINCT L1.USER_ID) AS LISTENED_USERS
FROM AUDIOBOOKS AB1
JOIN (
	SELECT
	AC.USER_ID,
	AC.AUDIOBOOK_UUID
	FROM AUDIO_CARDS AC
	JOIN AUDIOBOOKS AB ON AC.AUDIOBOOK_UUID = AB.UUID
	WHERE AB.TITLE = 'Coraline') 
AS AS1 ON AB1.UUID = AS1.AUDIOBOOK_UUID
JOIN (
	SELECT
	L.USER_ID,
	L.AUDIOBOOK_UUID
	FROM LISTENINGS L
	JOIN AUDIOBOOKS A ON L.AUDIOBOOK_UUID = A.UUID
	WHERE A.TITLE = 'Coraline'
	GROUP BY L.USER_ID, L.AUDIOBOOK_UUID, A.DURATION
	HAVING SUM(POSITION_TO - POSITION_FROM) > 0.1 * A.DURATION) 
AS L1 ON AB1.UUID = L1.AUDIOBOOK_UUID
GROUP BY AB1.TITLE;

-- 3.2 По ОС и названию книги: кол-во пользователей и сумма прослушивания в часах без тестовых прослушиваний
SELECT
	L.OS_NAME,
	AB.TITLE,
	COUNT(DISTINCT USER_ID) AS USERS,
	ROUND(SUM(L.POSITION_TO - L.POSITION_FROM) / 3600.0, 1) AS TOTAL_HOURS
FROM LISTENINGS L
JOIN AUDIOBOOKS AB ON L.AUDIOBOOK_UUID = AB.UUID
WHERE L.IS_TEST = 0
GROUP BY L.OS_NAME, AB.TITLE
ORDER BY AB.TITLE, L.OS_NAME;


-- 3.3 Книга, которую слушает больше всего людей
SELECT 
	AB.TITLE,
	COUNT(DISTINCT USER_ID) AS LISTENED_USERS
FROM AUDIOBOOKS AB
JOIN AUDIO_CARDS AC ON AB.UUID = AC.AUDIOBOOK_UUID
WHERE AC.STATE = 'listening'
GROUP BY AB.TITLE
ORDER BY LISTENED_USERS DESC 
LIMIT 1;

-- 3.4 Книга, которую чаще всего дослушивают до конца
SELECT
	AB.TITLE,
	COUNT(DISTINCT USER_ID) AS FINISHED_USERS
FROM AUDIOBOOKS AB
JOIN AUDIO_CARDS AC ON AB.UUID = AC.AUDIOBOOK_UUID
WHERE AC.STATE = 'finished'
GROUP BY AB.TITLE
ORDER BY FINISHED_USERS DESC 
LIMIT 1;



